export const PREDEFINED_EXERCISES = [
  { name: 'Bulgarian Split Squats', type: 'Lower Body' },
  { name: 'Romanian Deadlifts', type: 'Lower Body' },
  { name: 'Lying or Seated Leg Curls', type: 'Lower Body' },
  { name: 'Goblet Squats', type: 'Lower Body' },
  { name: 'Standing DB Overhead Alternate Press', type: 'Upper Body' },
  { name: 'Dumbbell L-Raise (Front to Lateral Raise Combo)', type: 'Upper Body' },
  { name: 'Single-Arm Dumbbell Front Raise', type: 'Upper Body' },
  { name: 'Single-Arm Dumbbell Lateral Raise', type: 'Upper Body' },
  { name: 'Single-Arm Dumbbell Lateral Raise (Arm at Shoulder Height)', type: 'Upper Body' },
  { name: 'Plank', type: 'Abs' },
  { name: 'Dead Bug', type: 'Abs' },
  { name: 'Bicycle Crunch', type: 'Abs' },
  { name: 'Alternate Leg and Arm Sideways', type: 'Abs' },
  { name: 'Crunches with Legs Up', type: 'Abs' },
  { name: 'Reverse Crunches', type: 'Abs' },
];
